[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Force Railway to use our Dockerfile instead of auto-detecting package managers
[build.environment]
NPM_CONFIG_PRODUCTION = "false"

# Health check configuration
[deploy.healthcheck]
path = "/health"
timeout = 300
interval = 30
retries = 3




